# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.102.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    ENV["XCODE_SCHEME"] = "esparta-ninja"
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    #cert(output_path: "./certificates")
    #sigh(output_path: "./certificates")

    #if is_ci? ... else ... end
    setup_jenkins

    create_keychain(
      name: "JenkinsKeys",
      default_keychain: true,
      unlock: true,
      timeout: 36000,
      lock_when_sleeps: true,
      password: "niggaz"
    )

    import_certificate(
      keychain_name: "JenkinsKeys",
      certificate_path: "certificates/C7UMY7FTXP.cer"
    )

    #increment_build_number ## esta pegando o projeto pod
    new_version_number = increment_version_number(
      bump_type: "patch"
    )
    
    gym(scheme: "esparta-ninja",
      provisioning_profile_path: "./certificates/Development_io.esparta.esparta-ninja.mobileprovision",
      use_legacy_build_api: true
    )
    
    crashlytics(
      api_token: "8382bfd3c9c59a468310fe80892b0f6e666c1c33",
      build_secret: "7229488462f7b621187ef2046889927e5fc0ac660997a13ced995ae79f8b45d0",
      groups: "esparta",
      notes: "Automatic iOS Build"
    )

    slack(
      message: "App esparta-ninja-ios successfully released!",
      channel: "#lab",  # Optional, by default will post to the default channel configured for the POST URL.
      success: true,        # Optional, defaults to true.
      payload: {            # Optional, lets you specify any number of your own Slack attachments.
        'Build Date' => Time.new.to_s,
        'Built by' => 'Bryan',
        'Version' => new_version_number,
      },
      default_payloads: [:git_branch, :git_author], # Optional, lets you specify a whitelist of default payloads to include. Pass an empty array to suppress all the default payloads. Don't add this key, or pass nil, if you want all the default payloads. The available default payloads are: `lane`, `test_result`, `git_branch`, `git_author`, `last_git_commit_message`.
    )
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
